language: python
python:
  #- "3.7" disable due to network error on travis
  - "3.6"
  - "3.5"
  - "2.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
    - 'pip install  -e ".[test]"'
script:
    - "python ./setup.py test"
